### ISSUE TITLE
Remove Background color on Micomasters logo

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/micromasters-zendesk-theme#3]
There is an unwanted background-color behind the logo. The color needs to 

<img width="1299" alt="Screen Shot 2021-02-10 at 10 42 09 AM" src="https://user-images.githubusercontent.com/49685474/107533149-a30c0700-6b8c-11eb-8aca-e0d282784814.png">
be removed from the CSS.

**Comment by arslanashraf7** [comment]
@abdulkdawson , Just curious, Is this theme currently deployed on some instance, If Yes, Can you share the url of the support centre where it can be seen in realtime?

**Comment by arslanashraf7** [comment]
@abdulkdawson This is fixed in the repo, You can verify the change in the description of this PR, https://github.com/mitodl/micromasters-zendesk-theme/pull/4

**Comment by abdulkdawson** [comment]
@arslanashraf7 I still see the background color behind the logo.

<img width="1651" alt="Screen Shot 2021-02-16 at 9 22 12 AM" src="https://user-images.githubusercontent.com/49685474/108075519-764a6a80-7038-11eb-9cd9-23ffd6d7616f.png">

**Comment by arslanashraf7** [comment]
@abdulkdawson, I think it's currently now deployed on Prod, The change is yet deployed on a test account here https://mmtestsupport.zendesk.com/hc/en-us. I believe once we re-deploy the theme this change will reflect on Prod as well.

**Comment by arslanashraf7** [comment]
@abdulkdawson, The theme is now deployed on production as well, You can visit this link to verify the change https://mitx-micromasters.zendesk.com/hc/en-us.

**Comment by abdulkdawson** [comment]
@arslanashraf7 this looks good. Thank you!
